/* Zepto v1.1.3 - zepto event ajax form ie - zeptojs.com/license */
var Zepto=function(){function d(b){return null==b?String(b):I[P.call(b)]||"object"}function j(b){return"function"==d(b)}function o(b){return null!=b&&b==b.window}function t(b){return null!=b&&b.nodeType==b.DOCUMENT_NODE}function u(b){return"object"==d(b)}function g(b){return u(b)&&!o(b)&&Object.getPrototypeOf(b)==Object.prototype}function p(b){return"number"==typeof b.length}function x(b){return b.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,
"-").toLowerCase()}function A(b){return b in w?w[b]:w[b]=RegExp("(^|\\s)"+b+"(\\s|$)")}function m(b){return"children"in b?B.call(b.children):f.map(b.childNodes,function(b){if(1==b.nodeType)return b})}function C(b,a,c){for(h in a)c&&(g(a[h])||E(a[h]))?(g(a[h])&&!g(b[h])&&(b[h]={}),E(a[h])&&!E(b[h])&&(b[h]=[]),C(b[h],a[h],c)):a[h]!==k&&(b[h]=a[h])}function q(b,a){return null==a?f(b):f(b).filter(a)}function l(b,a,c,e){return j(a)?a.call(b,c,e):a}function r(b,a){var c=b.className,e=c&&c.baseVal!==k;if(a===
k)return e?c.baseVal:c;e?c.baseVal=a:b.className=a}function s(b){var a;try{return b?"true"==b||("false"==b?!1:"null"==b?null:!/^0/.test(b)&&!isNaN(a=Number(b))?a:/^[\[\{]/.test(b)?f.parseJSON(b):b):b}catch(c){return b}}function v(b,a){a(b);for(var c in b.childNodes)v(b.childNodes[c],a)}var k,h,f,y,z=[],B=z.slice,c=z.filter,a=window.document,e={},w={},K={"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},F=/^\s*<(\w+|!)[^>]*>/,Q=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,i=
/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,L=/^(?:body|html)$/i,R=/([A-Z])/g,S="val css html text data width height offset".split(" "),J=a.createElement("table"),M=a.createElement("tr"),N={tr:a.createElement("tbody"),tbody:J,thead:J,tfoot:J,td:M,th:M,"*":a.createElement("div")},T=/complete|loaded|interactive/,U=/^[\w-]*$/,I={},P=I.toString,n={},G,H,O=a.createElement("div"),V={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",
cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},E=Array.isArray||function(b){return b instanceof Array};n.matches=function(b,a){if(!a||!b||1!==b.nodeType)return!1;var c=b.webkitMatchesSelector||b.mozMatchesSelector||b.oMatchesSelector||b.matchesSelector;if(c)return c.call(b,a);var e;e=b.parentNode;(c=!e)&&(e=O).appendChild(b);e=~n.qsa(e,a).indexOf(b);c&&O.removeChild(b);return e};G=
function(b){return b.replace(/-+(.)?/g,function(b,a){return a?a.toUpperCase():""})};H=function(b){return c.call(b,function(a,c){return b.indexOf(a)==c})};n.fragment=function(b,c,e){var d,w,h;Q.test(b)&&(d=f(a.createElement(RegExp.$1)));d||(b.replace&&(b=b.replace(i,"<$1></$2>")),c===k&&(c=F.test(b)&&RegExp.$1),c in N||(c="*"),h=N[c],h.innerHTML=""+b,d=f.each(B.call(h.childNodes),function(){h.removeChild(this)}));g(e)&&(w=f(d),f.each(e,function(b,a){if(S.indexOf(b)>-1)w[b](a);else w.attr(b,a)}));return d};
n.Z=function(b,a){b=b||[];b.__proto__=f.fn;b.selector=a||"";return b};n.isZ=function(b){return b instanceof n.Z};n.init=function(b,e){var D;if(b)if("string"==typeof b)if(b=b.trim(),"<"==b[0]&&F.test(b))D=n.fragment(b,RegExp.$1,e),b=null;else{if(e!==k)return f(e).find(b);D=n.qsa(a,b)}else{if(j(b))return f(a).ready(b);if(n.isZ(b))return b;if(E(b))D=c.call(b,function(b){return null!=b});else if(u(b))D=[b],b=null;else if(F.test(b))D=n.fragment(b.trim(),RegExp.$1,e),b=null;else{if(e!==k)return f(e).find(b);
D=n.qsa(a,b)}}else return n.Z();return n.Z(D,b)};f=function(b,a){return n.init(b,a)};f.extend=function(b){var a,c=B.call(arguments,1);"boolean"==typeof b&&(a=b,b=c.shift());c.forEach(function(c){C(b,c,a)});return b};n.qsa=function(b,a){var c,e="#"==a[0],d=!e&&"."==a[0],f=e||d?a.slice(1):a,w=U.test(f);return t(b)&&w&&e?(c=b.getElementById(f))?[c]:[]:1!==b.nodeType&&9!==b.nodeType?[]:B.call(w&&!e?d?b.getElementsByClassName(f):b.getElementsByTagName(a):b.querySelectorAll(a))};f.contains=function(b,a){return b!==
a&&b.contains(a)};f.type=d;f.isFunction=j;f.isWindow=o;f.isArray=E;f.isPlainObject=g;f.isEmptyObject=function(b){for(var a in b)return!1;return!0};f.inArray=function(b,a,c){return z.indexOf.call(a,b,c)};f.camelCase=G;f.trim=function(b){return null==b?"":String.prototype.trim.call(b)};f.uuid=0;f.support={};f.expr={};f.map=function(b,a){var c,e=[],d;if(p(b))for(d=0;d<b.length;d++)c=a(b[d],d),null!=c&&e.push(c);else for(d in b)c=a(b[d],d),null!=c&&e.push(c);return 0<e.length?f.fn.concat.apply([],e):
e};f.each=function(b,a){var c;if(p(b))for(c=0;c<b.length&&!1!==a.call(b[c],c,b[c]);c++);else for(c in b)if(!1===a.call(b[c],c,b[c]))break;return b};f.grep=function(b,a){return c.call(b,a)};window.JSON&&(f.parseJSON=JSON.parse);f.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(b,a){I["[object "+a+"]"]=a.toLowerCase()});f.fn={forEach:z.forEach,reduce:z.reduce,push:z.push,sort:z.sort,indexOf:z.indexOf,concat:z.concat,map:function(b){return f(f.map(this,function(a,
c){return b.call(a,c,a)}))},slice:function(){return f(B.apply(this,arguments))},ready:function(b){T.test(a.readyState)&&a.body?b(f):a.addEventListener("DOMContentLoaded",function(){b(f)},false);return this},get:function(b){return b===k?B.call(this):this[b>=0?b:b+this.length]},toArray:function(){return this.get()},size:function(){return this.length},remove:function(){return this.each(function(){this.parentNode!=null&&this.parentNode.removeChild(this)})},each:function(b){z.every.call(this,function(a,
c){return b.call(a,c,a)!==false});return this},filter:function(b){return j(b)?this.not(this.not(b)):f(c.call(this,function(a){return n.matches(a,b)}))},add:function(b,a){return f(H(this.concat(f(b,a))))},is:function(b){return this.length>0&&n.matches(this[0],b)},not:function(b){var a=[];if(j(b)&&b.call!==k)this.each(function(c){b.call(this,c)||a.push(this)});else{var c=typeof b=="string"?this.filter(b):p(b)&&j(b.item)?B.call(b):f(b);this.forEach(function(b){c.indexOf(b)<0&&a.push(b)})}return f(a)},
has:function(b){return this.filter(function(){return u(b)?f.contains(this,b):f(this).find(b).size()})},eq:function(b){return b===-1?this.slice(b):this.slice(b,+b+1)},first:function(){var b=this[0];return b&&!u(b)?b:f(b)},last:function(){var b=this[this.length-1];return b&&!u(b)?b:f(b)},find:function(b){var a=this;return typeof b=="object"?f(b).filter(function(){var b=this;return z.some.call(a,function(a){return f.contains(a,b)})}):this.length==1?f(n.qsa(this[0],b)):this.map(function(){return n.qsa(this,
b)})},closest:function(b,a){var c=this[0],e=false;for(typeof b=="object"&&(e=f(b));c&&!(e?e.indexOf(c)>=0:n.matches(c,b));)c=c!==a&&!t(c)&&c.parentNode;return f(c)},parents:function(b){for(var a=[],c=this;c.length>0;)c=f.map(c,function(b){if((b=b.parentNode)&&!t(b)&&a.indexOf(b)<0){a.push(b);return b}});return q(a,b)},parent:function(b){return q(H(this.pluck("parentNode")),b)},children:function(b){return q(this.map(function(){return m(this)}),b)},contents:function(){return this.map(function(){return B.call(this.childNodes)})},
siblings:function(b){return q(this.map(function(b,a){return c.call(m(a.parentNode),function(b){return b!==a})}),b)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(b){return f.map(this,function(a){return a[b]})},show:function(){return this.each(function(){this.style.display=="none"&&(this.style.display="");if(getComputedStyle(this,"").getPropertyValue("display")=="none"){var b=this.style,c=this.nodeName,d,f;if(!e[c]){d=a.createElement(c);a.body.appendChild(d);f=getComputedStyle(d,
"").getPropertyValue("display");d.parentNode.removeChild(d);f=="none"&&(f="block");e[c]=f}b.display=e[c]}})},replaceWith:function(b){return this.before(b).remove()},wrap:function(b){var a=j(b);if(this[0]&&!a)var c=f(b).get(0),e=c.parentNode||this.length>1;return this.each(function(d){f(this).wrapAll(a?b.call(this,d):e?c.cloneNode(true):c)})},wrapAll:function(b){if(this[0]){f(this[0]).before(b=f(b));for(var a;(a=b.children()).length;)b=a.first();f(b).append(this)}return this},wrapInner:function(b){var a=
j(b);return this.each(function(c){var e=f(this),d=e.contents(),c=a?b.call(this,c):b;d.length?d.wrapAll(c):e.append(c)})},unwrap:function(){this.parent().each(function(){f(this).replaceWith(f(this).children())});return this},clone:function(){return this.map(function(){return this.cloneNode(true)})},hide:function(){return this.css("display","none")},toggle:function(b){return this.each(function(){var a=f(this);(b===k?a.css("display")=="none":b)?a.show():a.hide()})},prev:function(b){return f(this.pluck("previousElementSibling")).filter(b||
"*")},next:function(b){return f(this.pluck("nextElementSibling")).filter(b||"*")},html:function(b){return arguments.length===0?this.length>0?this[0].innerHTML:null:this.each(function(a){var c=this.innerHTML;f(this).empty().append(l(this,b,a,c))})},text:function(b){return arguments.length===0?this.length>0?this[0].textContent:null:this.each(function(){this.textContent=b===k?"":""+b})},attr:function(b,a){var c;return typeof b=="string"&&a===k?this.length==0||this[0].nodeType!==1?k:b=="value"&&this[0].nodeName==
"INPUT"?this.val():!(c=this[0].getAttribute(b))&&b in this[0]?this[0][b]:c:this.each(function(c){if(this.nodeType===1)if(u(b))for(h in b){var c=h,e=b[h];e==null?this.removeAttribute(c):this.setAttribute(c,e)}else{c=l(this,a,c,this.getAttribute(b));c==null?this.removeAttribute(b):this.setAttribute(b,c)}})},removeAttr:function(b){return this.each(function(){this.nodeType===1&&this.removeAttribute(b)})},prop:function(b,a){b=V[b]||b;return a===k?this[0]&&this[0][b]:this.each(function(c){this[b]=l(this,
a,c,this[b])})},data:function(b,a){var c=this.attr("data-"+b.replace(R,"-$1").toLowerCase(),a);return c!==null?s(c):k},val:function(b){return arguments.length===0?this[0]&&(this[0].multiple?f(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):this[0].value):this.each(function(a){this.value=l(this,b,a,this.value)})},offset:function(b){if(b)return this.each(function(a){var c=f(this),a=l(this,b,a,c.offset()),e=c.offsetParent().offset(),a={top:a.top-e.top,left:a.left-e.left};
c.css("position")=="static"&&(a.position="relative");c.css(a)});if(this.length==0)return null;var a=this[0].getBoundingClientRect();return{left:a.left+window.pageXOffset,top:a.top+window.pageYOffset,width:Math.round(a.width),height:Math.round(a.height)}},css:function(b,a){if(arguments.length<2){var c=this[0],e=getComputedStyle(c,"");if(!c)return;if(typeof b=="string")return c.style[G(b)]||e.getPropertyValue(b);if(E(b)){var w={};f.each(E(b)?b:[b],function(b,a){w[a]=c.style[G(a)]||e.getPropertyValue(a)});
return w}}var i="";if(d(b)=="string")!a&&a!==0?this.each(function(){this.style.removeProperty(x(b))}):i=x(b)+":"+(typeof a=="number"&&!K[x(b)]?a+"px":a);else for(h in b)!b[h]&&b[h]!==0?this.each(function(){this.style.removeProperty(x(h))}):i=i+(x(h)+":"+(typeof b[h]=="number"&&!K[x(h)]?b[h]+"px":b[h])+";");return this.each(function(){this.style.cssText=this.style.cssText+(";"+i)})},index:function(b){return b?this.indexOf(f(b)[0]):this.parent().children().indexOf(this[0])},hasClass:function(b){return!b?
false:z.some.call(this,function(b){return this.test(r(b))},A(b))},addClass:function(b){return!b?this:this.each(function(a){y=[];var c=r(this);l(this,b,a,c).split(/\s+/g).forEach(function(b){f(this).hasClass(b)||y.push(b)},this);y.length&&r(this,c+(c?" ":"")+y.join(" "))})},removeClass:function(b){return this.each(function(a){if(b===k)return r(this,"");y=r(this);l(this,b,a,y).split(/\s+/g).forEach(function(b){y=y.replace(A(b)," ")});r(this,y.trim())})},toggleClass:function(b,a){return!b?this:this.each(function(c){var e=
f(this);l(this,b,c,r(this)).split(/\s+/g).forEach(function(b){(a===k?!e.hasClass(b):a)?e.addClass(b):e.removeClass(b)})})},scrollTop:function(b){if(this.length){var a="scrollTop"in this[0];return b===k?a?this[0].scrollTop:this[0].pageYOffset:this.each(a?function(){this.scrollTop=b}:function(){this.scrollTo(this.scrollX,b)})}},scrollLeft:function(b){if(this.length){var a="scrollLeft"in this[0];return b===k?a?this[0].scrollLeft:this[0].pageXOffset:this.each(a?function(){this.scrollLeft=b}:function(){this.scrollTo(b,
this.scrollY)})}},position:function(){if(this.length){var b=this[0],a=this.offsetParent(),c=this.offset(),e=L.test(a[0].nodeName)?{top:0,left:0}:a.offset();c.top=c.top-(parseFloat(f(b).css("margin-top"))||0);c.left=c.left-(parseFloat(f(b).css("margin-left"))||0);e.top=e.top+(parseFloat(f(a[0]).css("border-top-width"))||0);e.left=e.left+(parseFloat(f(a[0]).css("border-left-width"))||0);return{top:c.top-e.top,left:c.left-e.left}}},offsetParent:function(){return this.map(function(){for(var b=this.offsetParent||
a.body;b&&!L.test(b.nodeName)&&f(b).css("position")=="static";)b=b.offsetParent;return b})}};f.fn.detach=f.fn.remove;["width","height"].forEach(function(b){var a=b.replace(/./,function(b){return b[0].toUpperCase()});f.fn[b]=function(c){var e,d=this[0];return c===k?o(d)?d["inner"+a]:t(d)?d.documentElement["scroll"+a]:(e=this.offset())&&e[b]:this.each(function(a){d=f(this);d.css(b,l(this,c,a,d[b]()))})}});["after","prepend","before","append"].forEach(function(b,a){var c=a%2;f.fn[b]=function(){var b,
e=f.map(arguments,function(a){b=d(a);return b=="object"||b=="array"||a==null?a:n.fragment(a)}),w,i=this.length>1;return e.length<1?this:this.each(function(b,d){w=c?d:d.parentNode;d=a==0?d.nextSibling:a==1?d.firstChild:a==2?d:null;e.forEach(function(b){if(i)b=b.cloneNode(true);else if(!w)return f(b).remove();v(w.insertBefore(b,d),function(b){b.nodeName!=null&&(b.nodeName.toUpperCase()==="SCRIPT"&&(!b.type||b.type==="text/javascript")&&!b.src)&&window.eval.call(window,b.innerHTML)})})})};f.fn[c?b+"To":
"insert"+(a?"Before":"After")]=function(a){f(a)[b](this);return this}});n.Z.prototype=f.fn;n.uniq=H;n.deserializeValue=s;f.zepto=n;return f}();window.Zepto=Zepto;void 0===window.$&&(window.$=Zepto);
(function(d){function j(c){return c._zid||(c._zid=A++)}function o(c,a,e,d){a=t(a);if(a.ns)var f=RegExp("(?:^| )"+a.ns.replace(" "," .* ?")+"(?: |$)");return(r[j(c)]||[]).filter(function(c){return c&&(!a.e||c.e==a.e)&&(!a.ns||f.test(c.ns))&&(!e||j(c.fn)===j(e))&&(!d||c.sel==d)})}function t(c){c=(""+c).split(".");return{e:c[0],ns:c.slice(1).sort().join(" ")}}function u(c,a,e,f,g,F,l){var i=j(c),q=r[i]||(r[i]=[]);a.split(/\s/).forEach(function(a){if("ready"==a)return d(document).ready(e);var i=t(a);
i.fn=e;i.sel=g;i.e in h&&(e=function(a){var c=a.relatedTarget;if(!c||c!==this&&!d.contains(this,c))return i.fn.apply(this,arguments)});var j=(i.del=F)||e;i.proxy=function(a){a=p(a);if(!a.isImmediatePropagationStopped()){a.data=f;var e=j.apply(c,a._args==m?[a]:[a].concat(a._args));!1===e&&(a.preventDefault(),a.stopPropagation());return e}};i.i=q.length;q.push(i);"addEventListener"in c&&c.addEventListener(h[i.e]||v&&k[i.e]||i.e,i.proxy,i.del&&!v&&i.e in k||!!l)})}function g(c,a,e,d,f){var g=j(c);(a||
"").split(/\s/).forEach(function(a){o(c,a,e,d).forEach(function(a){delete r[g][a.i];"removeEventListener"in c&&c.removeEventListener(h[a.e]||v&&k[a.e]||a.e,a.proxy,a.del&&!v&&a.e in k||!!f)})})}function p(c,a){if(a||!c.isDefaultPrevented)if(a||(a=c),d.each(B,function(e,d){var g=a[e];c[e]=function(){this[d]=f;return g&&g.apply(a,arguments)};c[d]=y}),a.defaultPrevented!==m?a.defaultPrevented:"returnValue"in a?!1===a.returnValue:a.getPreventDefault&&a.getPreventDefault())c.isDefaultPrevented=f;return c}
function x(c){var a,e={originalEvent:c};for(a in c)!z.test(a)&&c[a]!==m&&(e[a]=c[a]);return p(e,c)}var A=1,m,C=Array.prototype.slice,q=d.isFunction,l=function(c){return"string"==typeof c},r={},s={},v="onfocusin"in window,k={focus:"focusin",blur:"focusout"},h={mouseenter:"mouseover",mouseleave:"mouseout"};s.click=s.mousedown=s.mouseup=s.mousemove="MouseEvents";d.event={add:u,remove:g};d.proxy=function(c,a){if(q(c)){var e=function(){return c.apply(a,arguments)};e._zid=j(c);return e}if(l(a))return d.proxy(c[a],
c);throw new TypeError("expected function");};d.fn.bind=function(c,a,e){return this.on(c,a,e)};d.fn.unbind=function(c,a){return this.off(c,a)};d.fn.one=function(c,a,e,d){return this.on(c,a,e,d,1)};var f=function(){return!0},y=function(){return!1},z=/^([A-Z]|returnValue$|layer[XY]$)/,B={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"};d.fn.delegate=function(c,a,e){return this.on(a,c,e)};d.fn.undelegate=function(c,a,
e){return this.off(a,c,e)};d.fn.live=function(c,a){d(document.body).delegate(this.selector,c,a);return this};d.fn.die=function(c,a){d(document.body).undelegate(this.selector,c,a);return this};d.fn.on=function(c,a,e,f,h){var j,k,i=this;if(c&&!l(c))return d.each(c,function(c,d){i.on(c,a,e,d,h)}),i;!l(a)&&(!q(f)&&!1!==f)&&(f=e,e=a,a=m);if(q(e)||!1===e)f=e,e=m;!1===f&&(f=y);return i.each(function(i,l){h&&(j=function(a){g(l,a.type,f);return f.apply(this,arguments)});a&&(k=function(c){var e,i=d(c.target).closest(a,
l).get(0);if(i&&i!==l){e=d.extend(x(c),{currentTarget:i,liveFired:l});return(j||f).apply(i,[e].concat(C.call(arguments,1)))}});u(l,c,f,e,a,k||j)})};d.fn.off=function(c,a,e){var f=this;if(c&&!l(c))return d.each(c,function(c,e){f.off(c,a,e)}),f;!l(a)&&(!q(e)&&!1!==e)&&(e=a,a=m);!1===e&&(e=y);return f.each(function(){g(this,c,e,a)})};d.fn.trigger=function(c,a){c=l(c)||d.isPlainObject(c)?d.Event(c):p(c);c._args=a;return this.each(function(){"dispatchEvent"in this?this.dispatchEvent(c):d(this).triggerHandler(c,
a)})};d.fn.triggerHandler=function(c,a){var e,f;this.each(function(g,h){e=x(l(c)?d.Event(c):c);e._args=a;e.target=h;d.each(o(h,c.type||c),function(a,c){f=c.proxy(e);if(e.isImmediatePropagationStopped())return!1})});return f};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(c){d.fn[c]=function(a){return a?this.bind(c,a):this.trigger(c)}});["focus","blur"].forEach(function(c){d.fn[c]=
function(a){a?this.bind(c,a):this.each(function(){try{this[c]()}catch(a){}});return this}});d.Event=function(c,a){l(c)||(a=c,c=a.type);var e=document.createEvent(s[c]||"Events"),d=!0;if(a)for(var f in a)"bubbles"==f?d=!!a[f]:e[f]=a[f];e.initEvent(c,d,!0);return p(e)}})(Zepto);
(function(d){function j(c,a,e,f){if(c.global)return c=a||l,e=d.Event(e),d(c).trigger(e,f),!e.isDefaultPrevented()}function o(c,a){var e=a.context;if(!1===a.beforeSend.call(e,c,a)||!1===j(a,e,"ajaxBeforeSend",[c,a]))return!1;j(a,e,"ajaxSend",[c,a])}function t(c,a,e,d){var f=e.context;e.success.call(f,c,"success",a);d&&d.resolveWith(f,[c,"success",a]);j(e,f,"ajaxSuccess",[a,e,c]);g("success",a,e)}function u(c,a,e,d,f){var h=d.context;d.error.call(h,e,a,c);f&&f.rejectWith(h,[e,a,c]);j(d,h,"ajaxError",
[e,d,c||a]);g(a,e,d)}function g(c,a,e){var f=e.context;e.complete.call(f,a,c);j(e,f,"ajaxComplete",[a,e]);e.global&&!--d.active&&j(e,null,"ajaxStop")}function p(){}function x(c){c&&(c=c.split(";",2)[0]);return c&&(c==y?"html":c==f?"json":k.test(c)?"script":h.test(c)&&"xml")||"text"}function A(c,a){return""==a?c:(c+"&"+a).replace(/[&?]{1,2}/,"?")}function m(c,a,e,f){d.isFunction(a)&&(f=e,e=a,a=void 0);d.isFunction(e)||(f=e,e=void 0);return{url:c,data:a,success:e,dataType:f}}function C(c,a,e,f){var h,
g=d.isArray(a),j=d.isPlainObject(a);d.each(a,function(a,l){h=d.type(l);f&&(a=e?f:f+"["+(j||"object"==h||"array"==h?a:"")+"]");!f&&g?c.add(l.name,l.value):"array"==h||!e&&"object"==h?C(c,l,e,a):c.add(a,l)})}var q=0,l=window.document,r,s,v=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,k=/^(?:text|application)\/javascript/i,h=/^(?:text|application)\/xml/i,f="application/json",y="text/html",z=/^\s*$/;d.active=0;d.ajaxJSONP=function(c,a){if(!("type"in c))return d.ajax(c);var e=c.jsonpCallback,
f=(d.isFunction(e)?e():e)||"jsonp"+ ++q,h=l.createElement("script"),g=window[f],j,i=function(a){d(h).triggerHandler("error",a||"abort")},k={abort:i},m;a&&a.promise(k);d(h).on("load error",function(e,i){clearTimeout(m);d(h).off().remove();"error"==e.type||!j?u(null,i||"error",k,c,a):t(j[0],k,c,a);window[f]=g;j&&d.isFunction(g)&&g(j[0]);g=j=void 0});if(!1===o(k,c))return i("abort"),k;window[f]=function(){j=arguments};h.src=c.url.replace(/\?(.+)=\?/,"?$1="+f);l.head.appendChild(h);0<c.timeout&&(m=setTimeout(function(){i("timeout")},
c.timeout));return k};d.ajaxSettings={type:"GET",beforeSend:p,success:p,error:p,complete:p,context:null,global:!0,xhr:function(){return new window.XMLHttpRequest},accepts:{script:"text/javascript, application/javascript, application/x-javascript",json:f,xml:"application/xml, text/xml",html:y,text:"text/plain"},crossDomain:!1,timeout:0,processData:!0,cache:!0};d.ajax=function(c){var a=d.extend({},c||{}),e=d.Deferred&&d.Deferred();for(r in d.ajaxSettings)void 0===a[r]&&(a[r]=d.ajaxSettings[r]);a.global&&
0===d.active++&&j(a,null,"ajaxStart");a.crossDomain||(a.crossDomain=/^([\w-]+:)?\/\/([^\/]+)/.test(a.url)&&RegExp.$2!=window.location.host);a.url||(a.url=window.location.toString());a.processData&&(a.data&&"string"!=d.type(a.data))&&(a.data=d.param(a.data,a.traditional));if(a.data&&(!a.type||"GET"==a.type.toUpperCase()))a.url=A(a.url,a.data),a.data=void 0;!1===a.cache&&(a.url=A(a.url,"_="+Date.now()));var f=a.dataType,c=/\?.+=\?/.test(a.url);if("jsonp"==f||c)return c||(a.url=A(a.url,a.jsonp?a.jsonp+
"=?":!1===a.jsonp?"":"callback=?")),d.ajaxJSONP(a,e);var c=a.accepts[f],h={},g=function(a,c){h[a.toLowerCase()]=[a,c]},l=/^([\w-]+:)\/\//.test(a.url)?RegExp.$1:window.location.protocol,i=a.xhr(),k=i.setRequestHeader,q;e&&e.promise(i);a.crossDomain||g("X-Requested-With","XMLHttpRequest");g("Accept",c||"*/*");if(c=a.mimeType||c)-1<c.indexOf(",")&&(c=c.split(",",2)[0]),i.overrideMimeType&&i.overrideMimeType(c);if(a.contentType||!1!==a.contentType&&a.data&&"GET"!=a.type.toUpperCase())g("Content-Type",
a.contentType||"application/x-www-form-urlencoded");if(a.headers)for(s in a.headers)g(s,a.headers[s]);i.setRequestHeader=g;i.onreadystatechange=function(){if(i.readyState==4){i.onreadystatechange=p;clearTimeout(q);var c,h=false;if(i.status>=200&&i.status<300||i.status==304||i.status==0&&l=="file:"){f=f||x(a.mimeType||i.getResponseHeader("content-type"));c=i.responseText;try{f=="script"?(0,eval)(c):f=="xml"?c=i.responseXML:f=="json"&&(c=z.test(c)?null:d.parseJSON(c))}catch(g){h=g}h?u(h,"parsererror",
i,a,e):t(c,i,a,e)}else u(i.statusText||null,i.status?"error":"abort",i,a,e)}};if(!1===o(i,a))return i.abort(),u(null,"abort",i,a,e),i;if(a.xhrFields)for(s in a.xhrFields)i[s]=a.xhrFields[s];i.open(a.type,a.url,"async"in a?a.async:!0,a.username,a.password);for(s in h)k.apply(i,h[s]);0<a.timeout&&(q=setTimeout(function(){i.onreadystatechange=p;i.abort();u(null,"timeout",i,a,e)},a.timeout));i.send(a.data?a.data:null);return i};d.get=function(){return d.ajax(m.apply(null,arguments))};d.post=function(){var c=
m.apply(null,arguments);c.type="POST";return d.ajax(c)};d.getJSON=function(){var c=m.apply(null,arguments);c.dataType="json";return d.ajax(c)};d.fn.load=function(c,a,e){if(!this.length)return this;var f=this,h=c.split(/\s/),g,c=m(c,a,e),j=c.success;1<h.length&&(c.url=h[0],g=h[1]);c.success=function(a){f.html(g?d("<div>").html(a.replace(v,"")).find(g):a);j&&j.apply(f,arguments)};d.ajax(c);return this};var B=encodeURIComponent;d.param=function(c,a){var e=[];e.add=function(a,c){this.push(B(a)+"="+B(c))};
C(e,c,a);return e.join("&").replace(/%20/g,"+")}})(Zepto);
(function(d){d.fn.serializeArray=function(){var j=[],o;d([].slice.call(this.get(0).elements)).each(function(){o=d(this);var t=o.attr("type");"fieldset"!=this.nodeName.toLowerCase()&&(!this.disabled&&"submit"!=t&&"reset"!=t&&"button"!=t&&("radio"!=t&&"checkbox"!=t||this.checked))&&j.push({name:o.attr("name"),value:o.val()})});return j};d.fn.serialize=function(){var d=[];this.serializeArray().forEach(function(o){d.push(encodeURIComponent(o.name)+"="+encodeURIComponent(o.value))});return d.join("&")};
d.fn.submit=function(j){j?this.bind("submit",j):this.length&&(j=d.Event("submit"),this.eq(0).trigger(j),j.isDefaultPrevented()||this.get(0).submit());return this}})(Zepto);(function(d){"__proto__"in{}||d.extend(d.zepto,{Z:function(j,o){j=j||[];d.extend(j,d.fn);j.selector=o||"";j.__Z=!0;return j},isZ:function(j){return"array"===d.type(j)&&"__Z"in j}});try{getComputedStyle(void 0)}catch(j){var o=getComputedStyle;window.getComputedStyle=function(d){try{return o(d)}catch(j){return null}}}})(Zepto);
(function(d){function j(){m=null;g.last&&(g.el.trigger("longTap"),g={})}function o(){p&&clearTimeout(p);x&&clearTimeout(x);A&&clearTimeout(A);m&&clearTimeout(m);p=x=A=m=null;g={}}function t(d){return("touch"==d.pointerType||d.pointerType==d.MSPOINTER_TYPE_TOUCH)&&d.isPrimary}function u(d,g){return d.type=="pointer"+g||d.type.toLowerCase()=="mspointer"+g}var g={},p,x,A,m,C;d(document).ready(function(){var q,l,r=0,s=0,v,k;"MSGesture"in window&&(C=new MSGesture,C.target=document.body);d(document).bind("MSGestureEnd",
function(d){if(d=d.velocityX>1?"Right":d.velocityX<-1?"Left":d.velocityY>1?"Down":d.velocityY<-1?"Up":null){g.el.trigger("swipe");g.el.trigger("swipe"+d)}}).on("touchstart MSPointerDown pointerdown",function(h){if(!(k=u(h,"down"))||t(h)){v=k?h:h.touches[0];if(h.touches&&h.touches.length===1&&g.x2){g.x2=void 0;g.y2=void 0}q=Date.now();l=q-(g.last||q);g.el=d("tagName"in v.target?v.target:v.target.parentNode);p&&clearTimeout(p);g.x1=v.pageX;g.y1=v.pageY;if(l>0&&l<=250)g.isDoubleTap=true;g.last=q;m=setTimeout(j,
750);C&&k&&C.addPointer(h.pointerId)}}).on("touchmove MSPointerMove pointermove",function(d){if(!(k=u(d,"move"))||t(d)){v=k?d:d.touches[0];m&&clearTimeout(m);m=null;g.x2=v.pageX;g.y2=v.pageY;r=r+Math.abs(g.x1-g.x2);s=s+Math.abs(g.y1-g.y2)}}).on("touchend MSPointerUp pointerup",function(h){if(!(k=u(h,"up"))||t(h)){m&&clearTimeout(m);m=null;g.x2&&Math.abs(g.x1-g.x2)>30||g.y2&&Math.abs(g.y1-g.y2)>30?A=setTimeout(function(){g.el.trigger("swipe");g.el.trigger("swipe"+(Math.abs(g.x1-g.x2)>=Math.abs(g.y1-
g.y2)?g.x1-g.x2>0?"Left":"Right":g.y1-g.y2>0?"Up":"Down"));g={}},0):"last"in g&&(r<30&&s<30?x=setTimeout(function(){var f=d.Event("tap");f.cancelTouch=o;g.el.trigger(f);if(g.isDoubleTap){g.el&&g.el.trigger("doubleTap");g={}}else p=setTimeout(function(){p=null;g.el&&g.el.trigger("singleTap");g={}},250)},0):g={});r=s=0}}).on("touchcancel MSPointerCancel pointercancel",o);d(window).on("scroll",o)});"swipe swipeLeft swipeRight swipeUp swipeDown doubleTap tap singleTap longTap".split(" ").forEach(function(g){d.fn[g]=
function(d){return this.on(g,d)}})})(Zepto);